-- ============================================================
-- SCHEMA COMPLETO + RLS — Mural Escola Startup
-- Execute no SQL Editor do Supabase Dashboard (uma vez)
-- Pode ser executado multiplas vezes (idempotente).
-- ============================================================
-- IMPORTANTE: Este app usa a anon key do Supabase no cliente.
-- As policies abaixo permitem operacoes para qualquer usuario
-- autenticado como 'anon' (que e o caso da anon key).
-- Para producao com autenticacao real, restrinja por auth.uid().
-- ============================================================

-- 1. teams
CREATE TABLE IF NOT EXISTS teams (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#2196F3',
  logo TEXT,
  members TEXT DEFAULT '',
  current_stage INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "teams_select_todos" ON teams;
DROP POLICY IF EXISTS "teams_insert_todos" ON teams;
DROP POLICY IF EXISTS "teams_update_todos" ON teams;
DROP POLICY IF EXISTS "teams_delete_todos" ON teams;
CREATE POLICY "teams_select_todos" ON teams FOR SELECT USING (true);
CREATE POLICY "teams_insert_todos" ON teams FOR INSERT WITH CHECK (true);
CREATE POLICY "teams_update_todos" ON teams FOR UPDATE USING (true);
CREATE POLICY "teams_delete_todos" ON teams FOR DELETE USING (true);

-- 2. stages_status
CREATE TABLE IF NOT EXISTS stages_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id, stage_id)
);

ALTER TABLE stages_status ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stages_status_select_todos" ON stages_status;
DROP POLICY IF EXISTS "stages_status_insert_todos" ON stages_status;
DROP POLICY IF EXISTS "stages_status_upsert_todos" ON stages_status;
DROP POLICY IF EXISTS "stages_status_delete_todos" ON stages_status;
CREATE POLICY "stages_status_select_todos" ON stages_status FOR SELECT USING (true);
CREATE POLICY "stages_status_insert_todos" ON stages_status FOR INSERT WITH CHECK (true);
CREATE POLICY "stages_status_upsert_todos" ON stages_status FOR UPDATE USING (true);
CREATE POLICY "stages_status_delete_todos" ON stages_status FOR DELETE USING (true);

-- 3. team_stage_deliverables
CREATE TABLE IF NOT EXISTS team_stage_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  item_name TEXT NOT NULL,
  content TEXT DEFAULT '',
  approved BOOLEAN DEFAULT false,
  feedback TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id, stage_id, item_name)
);

ALTER TABLE team_stage_deliverables ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "deliverables_select_todos" ON team_stage_deliverables;
DROP POLICY IF EXISTS "deliverables_insert_todos" ON team_stage_deliverables;
DROP POLICY IF EXISTS "deliverables_update_todos" ON team_stage_deliverables;
DROP POLICY IF EXISTS "deliverables_delete_todos" ON team_stage_deliverables;
CREATE POLICY "deliverables_select_todos" ON team_stage_deliverables FOR SELECT USING (true);
CREATE POLICY "deliverables_insert_todos" ON team_stage_deliverables FOR INSERT WITH CHECK (true);
CREATE POLICY "deliverables_update_todos" ON team_stage_deliverables FOR UPDATE USING (true);
CREATE POLICY "deliverables_delete_todos" ON team_stage_deliverables FOR DELETE USING (true);

-- 4. links
CREATE TABLE IF NOT EXISTS links (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "links_select_todos" ON links;
DROP POLICY IF EXISTS "links_insert_todos" ON links;
DROP POLICY IF EXISTS "links_update_todos" ON links;
DROP POLICY IF EXISTS "links_delete_todos" ON links;
CREATE POLICY "links_select_todos" ON links FOR SELECT USING (true);
CREATE POLICY "links_insert_todos" ON links FOR INSERT WITH CHECK (true);
CREATE POLICY "links_update_todos" ON links FOR UPDATE USING (true);
CREATE POLICY "links_delete_todos" ON links FOR DELETE USING (true);

-- 5. custom_stage_details
CREATE TABLE IF NOT EXISTS custom_stage_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id INTEGER NOT NULL,
  item_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (stage_id, item_name)
);

ALTER TABLE custom_stage_details ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "custom_details_select_todos" ON custom_stage_details;
DROP POLICY IF EXISTS "custom_details_insert_todos" ON custom_stage_details;
DROP POLICY IF EXISTS "custom_details_update_todos" ON custom_stage_details;
DROP POLICY IF EXISTS "custom_details_delete_todos" ON custom_stage_details;
CREATE POLICY "custom_details_select_todos" ON custom_stage_details FOR SELECT USING (true);
CREATE POLICY "custom_details_insert_todos" ON custom_stage_details FOR INSERT WITH CHECK (true);
CREATE POLICY "custom_details_update_todos" ON custom_stage_details FOR UPDATE USING (true);
CREATE POLICY "custom_details_delete_todos" ON custom_stage_details FOR DELETE USING (true);

-- 6. lean_canvas (sub-projeto Lean Canvas Interativo)
CREATE TABLE IF NOT EXISTS lean_canvas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL,
  canvas_data JSONB DEFAULT '{}',
  analysis JSONB DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id)
);

ALTER TABLE lean_canvas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "lean_canvas_select_todos" ON lean_canvas;
DROP POLICY IF EXISTS "lean_canvas_insert_todos" ON lean_canvas;
DROP POLICY IF EXISTS "lean_canvas_update_todos" ON lean_canvas;
CREATE POLICY "lean_canvas_select_todos" ON lean_canvas FOR SELECT USING (true);
CREATE POLICY "lean_canvas_insert_todos" ON lean_canvas FOR INSERT WITH CHECK (true);
CREATE POLICY "lean_canvas_update_todos" ON lean_canvas FOR UPDATE USING (true);
