-- ============================================================
-- SCHEMA COMPLETO + RLS — Mural Escola Startup
-- Execute no SQL Editor do Supabase Dashboard (uma vez)
-- ============================================================

-- 1. teams
CREATE TABLE IF NOT EXISTS teams (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#2196F3',
  logo TEXT,
  members TEXT DEFAULT '',
  current_stage INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

CREATE POLICY "teams_select_todos" ON teams FOR SELECT USING (true);
CREATE POLICY "teams_insert_admin" ON teams FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "teams_update_admin" ON teams FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "teams_delete_admin" ON teams FOR DELETE USING (auth.role() = 'service_role');

-- 2. stages_status
CREATE TABLE IF NOT EXISTS stages_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id, stage_id)
);

ALTER TABLE stages_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "stages_status_select_todos" ON stages_status FOR SELECT USING (true);
CREATE POLICY "stages_status_insert_admin" ON stages_status FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "stages_status_upsert_admin" ON stages_status FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "stages_status_delete_admin" ON stages_status FOR DELETE USING (auth.role() = 'service_role');

-- 3. team_stage_deliverables
CREATE TABLE IF NOT EXISTS team_stage_deliverables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  item_name TEXT NOT NULL,
  content TEXT DEFAULT '',
  approved BOOLEAN DEFAULT false,
  feedback TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id, stage_id, item_name)
);

ALTER TABLE team_stage_deliverables ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deliverables_select_todos" ON team_stage_deliverables FOR SELECT USING (true);
CREATE POLICY "deliverables_insert_own" ON team_stage_deliverables FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "deliverables_update_admin" ON team_stage_deliverables FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "deliverables_delete_admin" ON team_stage_deliverables FOR DELETE USING (auth.role() = 'service_role');

-- 4. links
CREATE TABLE IF NOT EXISTS links (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "links_select_todos" ON links FOR SELECT USING (true);
CREATE POLICY "links_insert_own" ON links FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "links_update_own" ON links FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "links_delete_own" ON links FOR DELETE USING (auth.role() = 'service_role');

-- 5. custom_stage_details
CREATE TABLE IF NOT EXISTS custom_stage_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id INTEGER NOT NULL,
  item_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (stage_id, item_name)
);

ALTER TABLE custom_stage_details ENABLE ROW LEVEL SECURITY;

CREATE POLICY "custom_details_select_todos" ON custom_stage_details FOR SELECT USING (true);
CREATE POLICY "custom_details_insert_admin" ON custom_stage_details FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "custom_details_update_admin" ON custom_stage_details FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "custom_details_delete_admin" ON custom_stage_details FOR DELETE USING (auth.role() = 'service_role');

-- 6. lean_canvas (sub-projeto Lean Canvas Interativo)
CREATE TABLE IF NOT EXISTS lean_canvas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL,
  canvas_data JSONB DEFAULT '{}',
  analysis JSONB DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id)
);

ALTER TABLE lean_canvas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lean_canvas_select_todos" ON lean_canvas FOR SELECT USING (true);
CREATE POLICY "lean_canvas_upsert_own" ON lean_canvas FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "lean_canvas_update_own" ON lean_canvas FOR UPDATE USING (auth.role() = 'service_role');

-- ============================================================
-- NOTAS:
-- - Todas as policies usam auth.role() = 'service_role' porque
--   o app atual usa anon key diretamente (sem Supabase Auth).
-- - Para produção completa, migre para Supabase Auth e use
--   auth.uid() nas policies referenciando teams.user_id.
-- - Remova o arquivo 001_rls_policies.sql (substituído por este).
-- ============================================================
