-- ============================================================
-- TABELA FICHA GASTRONÔMICA E POLICIES
-- Execute no SQL Editor do Supabase Dashboard para habilitar a persistência
-- ============================================================

CREATE TABLE IF NOT EXISTS ficha_gastronomica (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id TEXT NOT NULL,
  recipe_data JSONB DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (team_id)
);

ALTER TABLE ficha_gastronomica ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "ficha_gastronomica_select_todos" ON ficha_gastronomica;
DROP POLICY IF EXISTS "ficha_gastronomica_insert_todos" ON ficha_gastronomica;
DROP POLICY IF EXISTS "ficha_gastronomica_update_todos" ON ficha_gastronomica;

CREATE POLICY "ficha_gastronomica_select_todos" ON ficha_gastronomica FOR SELECT USING (true);
CREATE POLICY "ficha_gastronomica_insert_todos" ON ficha_gastronomica FOR INSERT WITH CHECK (true);
CREATE POLICY "ficha_gastronomica_update_todos" ON ficha_gastronomica FOR UPDATE USING (true);
