-- ============================================================
-- TABELA deleted_stage_details - Suporte a exclusão de tarefas
-- Execute no SQL Editor do Supabase Dashboard (uma vez)
-- ============================================================

CREATE TABLE IF NOT EXISTS deleted_stage_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id INTEGER NOT NULL,
  item_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (stage_id, item_name)
);

ALTER TABLE deleted_stage_details ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "deleted_details_select_todos" ON deleted_stage_details;
DROP POLICY IF EXISTS "deleted_details_insert_todos" ON deleted_stage_details;
DROP POLICY IF EXISTS "deleted_details_update_todos" ON deleted_stage_details;
DROP POLICY IF EXISTS "deleted_details_delete_todos" ON deleted_stage_details;

CREATE POLICY "deleted_details_select_todos" ON deleted_stage_details FOR SELECT USING (true);
CREATE POLICY "deleted_details_insert_todos" ON deleted_stage_details FOR INSERT WITH CHECK (true);
CREATE POLICY "deleted_details_update_todos" ON deleted_stage_details FOR UPDATE USING (true);
CREATE POLICY "deleted_details_delete_todos" ON deleted_stage_details FOR DELETE USING (true);
